import { cookies, headers } from "next/headers";
import "./globals.css";

export const runtime = "nodejs";

import { type Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { Providers } from "@/app/providers";
import { decode, verifyCsrf } from "@/shared/security/csrf.server";
import { ThemeScript } from "@/shared/theme/theme-script";
import { getServerTheme } from "@/shared/theme/theme.server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { readonly children: React.ReactNode }) {
  const headerStore = await headers();
  const nonce = headerStore.get("x-nonce") ?? null;
  const initialTheme = await getServerTheme();
  const locale = await getLocale();
  const messages = await getMessages();
  const cookieStore = await cookies();
  const brand = "default";

  const encoded = cookieStore.get("csrf")?.value;
  const payload = encoded && verifyCsrf(encoded) ? decode(encoded) : null;

  return (
    <html
      suppressHydrationWarning
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      data-brand={brand}
      className={initialTheme === "dark" ? "dark" : undefined}
    >
      <body>
        <ThemeScript nonce={nonce} />

        {/* <ExternalScript src="https://www.google.com/recaptcha/api.js" nonce={nonce} /> */}
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers initialTheme={initialTheme} csrfToken={payload?.token ?? null}>
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
